// Central query key registry. React Query dedupes requests by key, so hooks
// that need the same data share one in-flight request/cache entry.
export const queryKeys = {
  summary: ["summary"] as const,
  executiveSummary: ["executive-summary"] as const,
  correlationEngine: ["correlation-engine"] as const,
  todayEvents: ["today-events"] as const,
  dailySummary: ["daily-summary"] as const,
  topThreatActorsToday: ["top-threat-actors-today"] as const,
  kev: ["kev"] as const,
  vulncheckKev: ["vulncheck-kev"] as const,
  exploits: ["exploits"] as const,
  cves: (paramsKey: string) => ["cves", paramsKey] as const,
  cveProgramActivity: ["cve-program-activity"] as const,
  threatFeed: ["threat-feed"] as const,
  trendingMalware: ["malware-trending"] as const,
  attackTechniques: ["attack-techniques"] as const,
  ransomware: ["ransomware"] as const,
  threatActors: ["threat-actors"] as const,
  news: ["news"] as const,
  health: ["health"] as const,
  iocSearch: (type: string, value: string) => ["ioc-search", type, value] as const,
  threatActorList: ["threat-actor-profiles"] as const,
  threatActorSearch: (query: string) => ["threat-actor-profiles", "search", query] as const,
  threatActorProfile: (attackId: string) => ["threat-actor-profiles", attackId] as const,
  githubIntelList: (paramsKey: string) => ["github-intel", paramsKey] as const,
  githubIntelStats: ["github-intel", "stats"] as const,
  githubRepoDetail: (fullName: string) => ["github-intel", fullName] as const,
  cveProfile: (cveId: string) => ["cve-profile", cveId] as const,
  malwareProfile: (family: string) => ["malware-profile", family] as const,
};
