// Central query key registry. React Query dedupes requests by key, so hooks
// that need the same data share one in-flight request/cache entry.
export const queryKeys = {
  summary: ["summary"] as const,
  executiveSummary: ["executive-summary"] as const,
  geoTargeting: ["geo-targeting"] as const,
  correlationEngine: ["correlation-engine"] as const,
  todayEvents: ["today-events"] as const,
  threatTimeline: (days: number) => ["threat-timeline", days] as const,
  kev: ["kev"] as const,
  vulncheckKev: ["vulncheck-kev"] as const,
  exploits: ["exploits"] as const,
  cves: (paramsKey: string) => ["cves", paramsKey] as const,
  cveProgramActivity: ["cve-program-activity"] as const,
  cveSeverityDistribution: ["cve-severity-distribution"] as const,
  threatFeed: ["threat-feed"] as const,
  trendingMalware: ["malware-trending"] as const,
  attackTechniques: ["attack-techniques"] as const,
  attackTacticHeatmap: ["attack-tactic-heatmap"] as const,
  ransomware: ["ransomware"] as const,
  threatActors: ["threat-actors"] as const,
  news: ["news"] as const,
  health: ["health"] as const,
  iocSearch: (type: string, value: string) => ["ioc-search", type, value] as const,
  githubIntelList: (paramsKey: string) => ["github-intel", paramsKey] as const,
  githubIntelStats: ["github-intel", "stats"] as const,
  githubRepoDetail: (fullName: string) => ["github-intel", fullName] as const,
  cveProfile: (cveId: string) => ["cve-profile", cveId] as const,
  malwareProfile: (family: string) => ["malware-profile", family] as const,
  chatHealth: ["chat-health"] as const,
  malwareIntelligence: ["malware-intelligence"] as const,
  threatActorIntelligence: ["threat-actor-intelligence"] as const,
  campaignIntelligence: ["campaign-intelligence"] as const,
  darkWebIntelligence: ["darkweb-intelligence"] as const,
  aiThreatSummaries: ["ai-threat-summaries"] as const,
  watchlist: ["watchlist"] as const,
  flashReports: ["flash-reports"] as const,
};
