// AI Investigation Summary / Detection Opportunities / Operational Guidance
// -- all three come from ONE on-demand call (see useGenerateInvestigationAiReport
// / server/investigationAi.js), fired only by the "Generate AI Report"
// button below, never automatically on search. Split into three panels so
// the parent console can place each at its required page position (spec
// order: AI Summary near the top, Detection Opportunities and Operational
// Guidance further down) while sharing one piece of report state.
import { BrainCircuit, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Section, FieldList, GroupedLists } from "../reportPrimitives";
import type { AiInvestigationReport } from "@/types/threat-intel";

interface AiReportState {
  report: AiInvestigationReport | undefined;
  isPending: boolean;
  error: string | null;
  onGenerate: () => void;
}

export function AiSummaryPanel({ report, isPending, error, onGenerate }: AiReportState) {
  return (
    <div className="rounded-xl border border-primary/20 bg-primary/[0.04] p-4">
      <div className="mb-2 flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <BrainCircuit className="h-4 w-4 text-primary" />
          <h3 className="text-sm font-semibold text-foreground">AI Investigation Summary</h3>
        </div>
        <Button type="button" variant="outline" onClick={onGenerate} disabled={isPending}>
          {isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <BrainCircuit className="h-3.5 w-3.5" />}
          {report ? "Regenerate AI Report" : "Generate AI Report"}
        </Button>
      </div>
      {error && <p className="text-xs text-critical">{error}</p>}
      {!report && !isPending && !error && (
        <p className="text-xs text-muted">
          Not generated yet — click "Generate AI Report" for a Tier 3 SOC analyst-style read: what this is, why it matters, likely attacker objective, business
          impact, and a recommended investigation path. This is a real LLM call and can take up to a minute.
        </p>
      )}
      {isPending && <p className="text-xs text-muted">Generating — this can take up to a minute...</p>}
      {report && (
        <div className="space-y-3 text-sm">
          <p className="text-foreground">{report.whatThisIs}</p>
          <p className="text-foreground">{report.whyItMatters}</p>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div>
              <p className="text-[11px] uppercase tracking-wide text-muted">Likely Attacker Objective</p>
              <p className="text-foreground">{report.likelyAttackerObjective}</p>
            </div>
            <div>
              <p className="text-[11px] uppercase tracking-wide text-muted">Business Impact</p>
              <p className="text-foreground">{report.businessImpact}</p>
            </div>
          </div>
          <p className="text-xs text-muted">{report.confidenceReasoning}</p>
          <FieldList title="Recommended Investigation Path" items={report.recommendedInvestigationPath} />
          <FieldList title="Immediate Containment Recommendations" items={report.immediateContainmentRecommendations} />
          <p className="text-[10px] text-muted">Generated by {report.provider} ({report.model}) at {new Date(report.generatedAt).toLocaleString()}.</p>
        </div>
      )}
    </div>
  );
}

export function DetectionOpportunitiesPanel({ report }: { report: AiInvestigationReport | undefined }) {
  if (!report) {
    return (
      <Section title="Detection Opportunities">
        <p className="text-xs text-muted">Generate an AI Report above to see Sentinel KQL, Sigma, Splunk SPL, Elastic, and YARA query concepts for this indicator.</p>
      </Section>
    );
  }
  const det = report.detectionOpportunities;
  return (
    <GroupedLists
      title="Detection Opportunities"
      groups={[
        ["Sentinel KQL", det.sentinelKql],
        ["Sigma", det.sigma],
        ["Splunk SPL", det.splunkSpl],
        ["Elastic", det.elastic],
        ["YARA", det.yara],
        ["Detection Gaps", det.detectionGaps],
        ["Hunting Hypotheses", det.huntingHypotheses],
      ]}
    />
  );
}

const ROLE_LABELS: Array<[keyof AiInvestigationReport["operationalGuidance"], string]> = [
  ["socAnalyst", "SOC Analyst"],
  ["threatHunter", "Threat Hunter"],
  ["threatIntel", "Threat Intelligence"],
  ["detectionEngineer", "Detection Engineer"],
  ["incidentResponse", "Incident Response"],
  ["vulnerabilityManagement", "Vulnerability Management"],
];

export function OperationalGuidancePanel({ report }: { report: AiInvestigationReport | undefined }) {
  if (!report) {
    return (
      <Section title="Operational Guidance">
        <p className="text-xs text-muted">Generate an AI Report above to see role-specific guidance for SOC Analyst, Threat Hunter, Threat Intelligence, Detection Engineer, Incident Response, and Vulnerability Management.</p>
      </Section>
    );
  }
  return (
    <Section title="Operational Guidance">
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {ROLE_LABELS.map(([key, label]) => (
          <div key={key} className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3">
            <p className="mb-1 text-xs font-semibold text-foreground">{label}</p>
            <p className="text-xs text-muted">{report.operationalGuidance[key]}</p>
          </div>
        ))}
      </div>
    </Section>
  );
}
