// Minimal usage example -- run with: node server/ai/example.js
// (or `npm run ai:example`, see package.json)
import "dotenv/config";
import { aiRouter, AllProvidersFailedError } from "./aiRouter.js";

const prompt =
  "Summarize in two sentences: a critical zero-day in a widely used firewall " +
  "management product is being actively exploited in the wild, and CISA has " +
  "added it to the Known Exploited Vulnerabilities catalog.";

try {
  // This is the only call the rest of the app ever needs to make -- it
  // doesn't know or care which of the four configured providers actually
  // answered.
  const result = await aiRouter.summarize(prompt);

  console.log(`\nGenerated by ${result.provider} (${result.model}) in ${(result.latency / 1000).toFixed(1)}s:\n`);
  console.log(result.summary);
} catch (error) {
  if (error instanceof AllProvidersFailedError) {
    console.error("\nEvery configured provider failed:");
    for (const attempt of error.attempts) console.error(`  - ${attempt.provider}: ${attempt.reason}`);
  } else {
    throw error;
  }
}
